# These queries are currently enabled by default on sourcegraph.com
groups:
    - name: monitoring_queries
      queries:
          # Single-term regex searches
          - query: searchZoekt patterntype:regexp # ~2 results
            name:  regex_small
          - query: can_handle_hl_color patterntype:regexp # ~ 50 results
            name:  regex_medium
          - query: try_init # 500+ results
            name:  regexp_large

          # Multi-term regex searches
          - query: matt senses # ~200 results
            name: regex_two_sameline
          - query: mk tim hike # ~70 results
            name: regex_three_sameline

          # Repo-scoped search
          - query: repo:^github\.com/sourcegraph/sourcegraph$ searchZoekt # ~2 results
            name: regex_repo_scope_small
          - query: repo:^github\.com/sourcegraph/sourcegraph$ fmt.Errorf # 500+ results
            name: regex_repo_scope_large

          # File-scoped search
          - query: >
                  repo:^github\.com/sourcegraph/sourcegraph$
                  file:search_results.go
                  error
            name: regex_file_scope

          # Structural search
          - query: > # ~ 15 results
                  patterntype:structural
                  repo:^github\.com/sourcegraph/sourcegraph$
                  WithLabels(...)
            name: structural_repo_scope_small
          - query: > # ~ 51 results
                  patterntype:structural
                  repo:^github\.com/sourcegraph/
                  strings.ToUpper(...)
            name: structural_multi_repo_small

# Queries that were previously used, and may still be useful, but are larger than
# what we want to run against sourcegraph.com every minute.
    # - name: global_same_line_regex
    #   queries:
    #       - query: func rtoorg patterntype:regexp
    #       - query: func bool bar patterntype:regexp
    #       - query: func bool patterntype:regexp
    #       - query: int32 error patterntype:regexp
    #       - query: func return patterntype:regexp
    #       - query: config override patterntype:regexp

    # - name: no_scope_content_medium_literal
    #   queries:
    #       - query: lang:java kms count:1000
    #       - query: cfssl lang:go -file:vendor/ count:1000
    #       - query: setDetails( count:1000
    #       - query: gcc_build count:1000
    #       - query: NTG6 count:1000
    #       - query: daimler count:1000 type:path
    #       - query: context.WithValue count:1000
    #       - query: streaming
    #       - query: converter
    #       - query: httpclient

    # - name: no_scope_content_small_literal
    #   queries:
    #       - query: --exclude-task=test
    #       - query: '"adding helm values to the environment"'
    #       - query: AuthorizationCodeRequestParameters
    #       - query: CommThread(LPVOID lang:c++
    #       - query: RemoteTaskAction
    #       - query: THNN_CudaSpatialConvolutionMM_updateOutput
    #       - query: Xml_StackOverflow lang:c#
    #       - query: ale_go_gopls
    #       - query: bazel:gcc_build
    #       - query: beaconDataUpdate
    #       - query: binlog_event.cpp
    #       - query: corpshare
    #       - query: init_file_metadata
    #       - query: k8s-controller-custom-resource
    #       - query: lang:java aws kms decrypt
    #       - query: mysql_global_status_slow_queries

    # - name: repo_file_scope_content_small_literal
    #   queries:
    #       - query: repo:^github\.com/ElemeFE/element$ file:^src/directives repeat-click
    #       - query: repo:^github\.com/apache/incubator-tvm$ file:^python/tvm/autotvm ApplyGraphBest
    #       - query: repo:^github\.com/cockroachdb/cockroach-gen$ file:^pkg/ccl/importccl/read_import_csv\.go p.record
    #       - query: repo:^github\.com/domoticz/domoticz$ file:^main/WebServer\.cpp gettransfer
    #       - query: repo:^github\.com/ianstormtaylor/slate$ file:^packages/slate-react/src getfragment
    #       - query: repo:^github\.com/kubernetes/kubernetes$ file:^cluster/gce/gci Installing
    #       - query: repo:^github\.com/pichillilorenzo/flutter_inappwebview$ file:^lib/src/in_app_webview_controller\.dart addJavaScriptHandler
    #       - query: repo:^github\.com/testdrivenio/fastapi-crud-async$ file:^src/app async

    # - name: structural_search
    #   queries:
    #       - query: repogroup:go-gh-100 language:go -file:test -file:vendor -file:Godeps strings.Index(..., ...) > -1 or strings.Index(..., ...) >= 0 or strings.Index(..., ...) != -1
